#
logging:
  config: classpath:logback.xml
#
spring:
  main:
    web-application-type: none
    banner-mode: off
  application:
    name: study-elasticsearch-springboot
  #
  elasticsearch:
    rest:
      uris: 111.229.94.31:9200
#      username:
#      password:
      connection-timeout: 30
      read-timeout: 30
